name = "r4e-microshift"

description = ""
version = "0.0.1"
modules = []
groups = []

# Force correct redhat-release

[[packages]]
name = "redhat-release"
version = "*"

# MicroShift dependencies

[[packages]]
name = "podman"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "conntrack-tools"
version = "*"

# configuration management

[[packages]]
name = "transmission-agent"
version = "0.1.6"

[[packages]]
name = "git"
version = "*"


# device management

[[packages]]
name = "rhc"
version = "*"

[[packages]]
name = "insights-client"
version = "*"

[[packages]]
name = "rhc-worker-playbook"
version = "*"

[[packages]]
name = "ansible"
version = "*"

[[packages]]
name = "subscription-manager-plugin-ostree"
version = "1.26.*"

[[packages]]
name = "subscription-manager"
version = "*"


# troubleshooting tools

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "iotop"
version = "*"

# Microshift

[[packages]]
name = "microshift"
version = "*"

[customizations]
[customizations.services]
enabled = ["crio", "transmission.timer", "microshift"]
